//****************** CODIGOS DE ACCESO, PERMISOS Y ALCANCE *************************
//**********************************************************************************
//*******Ventas
export const ACCESO__VENTAS = 10000;
//CRM
export const ACCESO__VENTAS_CRM = 11000;
//Cuentas
export const ACCESO__VENTAS_CRM_CUENTAS = 11100;
export const PERMISO__VENTAS_CRM_CUENTAS_BUSCAR = 11110;
export const ACCESSO__VENTAS_CRM_CUENTAS_CREAR = 11120;
export const ACCESSO__CRM_CUENTAS_SELECCIONAR = 11130;
export const PERMISO__VENTAS_CRM_CUENTAS_CREARSELECCIONAR_SELECCIONARPROPIETARIO = 11131;
export const PERMISO__VENTAS_CRM_CUENTAS_CREARSELECCIONAR_ACTIVAR = 11132;
export const PERMISO__VENTAS_CRM_CUENTAS_CREARSELECCIONAR_DESACTIVAR = 11133;
export const PERMISO__VENTAS_CRM_CUENTAS_CREARSELECCIONAR_GRABAR = 11134;
export const ACCESSO__VENTAS_CRM_CUENTAS_IMPORTAR = 11150;
export const ACCESSO__VENTAS_CRM_CUENTAS_LISTAR = 11160;
export const PERMISO__VENTAS_CRM_CUENTAS_LISTAR_EXPORTAR = 11161;
export const ACCESSO__VENTAS_CRM_CUENTAS_PENDIENTES = 11170;
//Contactos
export const ACCESO__VENTAS_CRM_CONTACTOS = 11200;
export const PERMISO__VENTAS_CRM_CONTACTOS_BUSCAR = 11210;
export const ACCESSO__VENTAS_CRM_CONTACTOS_CREAR = 11220;
export const ACCESSO__VENTAS_CRM_CONTACTOS_SELECCIONAR = 11230;
export const PERMISO__VENTAS_CRM_CONTACTOS_CREARSELECCIONAR_SELECCIONARPROPIETARIO = 11231;
export const PERMISO__VENTAS_CRM_CONTACTOS_CREARSELECCIONAR_ACTIVAR = 11232;
export const PERMISO__VENTAS_CRM_CONTACTOS_CREARSELECCIONAR_DESACTIVAR = 11233;
export const PERMISO__VENTAS_CRM_CONTACTOS_CREARSELECCIONAR_GRABAR = 11234;
export const ACCESSO__VENTAS_CRM_CONTACTOS_IMPORTAR = 11250;
export const ACCESSO__VENTAS_CRM_CONTACTOS_LISTAR = 11260;
export const PERMISO__VENTAS_CRM_CONTACTOS_LISTAR_EXPORTAR = 11261;
export const ACCESSO__VENTAS_CRM_CONTACTOS_PENDIENTES = 11270;
//Oportunidades
export const ACCESO__VENTAS_CRM_OPORTUNIDADES = 11300;
export const PERMISO_VENTAS_CRM_OPORTUNIDADES_BUSCAR = 11310;
export const ACCESSO__VENTAS_CRM_OPORTUNIDADES_CREAR = 11320;
export const ACCESSO__VENTAS_CRM_OPORTUNIDADES_SELECCIONAR = 11330;
export const PERMISO__VENTAS_CRM_OPORTUNIDADES_CREARSELECCIONAR_SELECCIONARPROPIETARIO = 11331;
export const PERMISO__VENTAS_CRM_OPORTUNIDADES_CREARSELECCIONAR_SELECCIONARPREVENTA = 11332;
export const PERMISO__VENTAS_CRM_OPORTUNIDADES_CREARSELECCIONAR_ACTIVAR = 11333;
export const PERMISO__VENTAS_CRM_OPORTUNIDADES_CREARSELECCIONAR_SOLICITARAPROBARETAPA = 11334;
export const PERMISO__VENTAS_CRM_OPORTUNIDADES_CREARSELECCIONAR_RETROTRAERETAPA = 11335;
export const PERMISO__VENTAS_CRM_OPORTUNIDADES_CREARSELECCIONAR_DECLARARPERDIDA = 11336;
export const PERMISO__VENTAS_CRM_OPORTUNIDADES_CREARSELECCIONAR_DECLARARANULADA = 11337;
export const PERMISO__VENTAS_CRM_OPORTUNIDADES_CREARSELECCIONAR_BYPASSEARETAPA = 11338;
export const PERMISO__VENTAS_CRM_OPORTUNIDADES_CREARSELECCIONAR_DESACTIVAR = 11339;
export const PERMISO__VENTAS_CRM_OPORTUNIDADES_CREARSELECCIONAR_GRABAR = 11340;
export const ACCESSO__VENTAS_CRM_OPORTUNIDADES_LISTAR = 11350;
export const PERMISO__VENTAS_CRM_OPORTUNIDADES_LISTAR_EXPORTAR = 11351;
export const ACCESSO__VENTAS_CRM_OPORTUNIDADES_PENDIENTES = 11360;
//Registros de fabricantes
export const ACCESO__VENTAS_CRM_REGISTRO_FABRICANTES = 11400;
//Cotizador
export const ACCESO__VENTAS_COTIZADOR = 12000;
//Nuevas cotizaciones
export const ACCESO__VENTAS_COTIZADOR_NUEVACOT = 12100;
//Abrir cotizaciones
export const ACCESO__VENTAS_COTIZADOR_ABRIRCOT = 12200;
export const PERMISO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_CREARPROPUESTA = 12210;
export const PERMISO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_CREARBUSCARPROPUESTA = 12220;
export const PERMISO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_SELECCIONARVENDEDOR = 12221;
export const PERMISO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_SELECCIONARPREVENTA = 12222;
export const PERMISO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_SELECCIONARPROPIETARIO = 12223;
export const PERMISO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_NUEVACOT_CLONAR = 12230;
export const PERMISO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_NUEVACOT_AGREGAR = 12250;
export const ACCESO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_PROPTECN = 12260;
export const ACCESO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_DOCUMPROP = 12300;
export const ACCESO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_RESUMEN = 12320;
export const ACCESO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_FINANCIADO = 12340;
export const ACCESO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_ANALISIS = 12350;
export const ACCESO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_CONDICIONES = 12360;
export const PERMISO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_CONDICIONES_TIPOCAMBIO = 12361;
export const ACCESO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_NOTASINTERNAS = 12380;
export const ACCESO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_FLUJO = 12390;
export const PERMISO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_FLUJO_SOLICITARAPROBACION = 12400;
export const PERMISO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_FLUJO_APROBAR = 12410;
export const PERMISO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_FLUJO_RECHAZAR = 12420;
export const PERMISO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_FLUJO_ENVIAR = 12430;
export const PERMISO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_FLUJO_DECLARARGANADA = 12440;
export const PERMISO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_FLUJO_DECLARARPERDIDA = 12450;
export const PERMISO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_FLUJO_DECLARARABANDONADA = 12460;
export const PERMISO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_FLUJO_ACEPTARORDEN = 12470;
export const PERMISO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_FLUJO_CONVERTIREXCEL = 12480;
export const PERMISO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_IMPRIMIRCOSTEO = 12500;
export const PERMISO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_PERMITIRCAMBIOS = 12600;
export const PERMISO__VENTAS_COTIZADOR_NUEVACOTABRIRCOT_GRABARCOT = 12700;
//Imprimir cotización
export const ACCESO__VENTAS_COTIZADOR_IMPRIMIRCOT = 12800;
export const PERMISO__VENTAS_COTIZADOR_IMPRIMIRCOT_IMPRIMIRCOT = 12801;
//Preventa
export const ACCESO__VENTAS_PREVENTA = 13000;
//Oportunidades de Preventa
export const ACCESO__VENTAS_PREVENTA_OPORTUNIDADES = 13050;
//Propuesta Técnica
export const ACCESO__VENTAS_PREVENTA_OPORTUNIDADES_PROPUESTATECNICA = 13100;
//Documentación de la propuesta Técnica
export const ACCESO__VENTAS_PREVENTA_OPORTUNIDADES_DOCUMENTACION = 13200;
export const PERMISO__VENTAS_PREVENTA_OPORTUNIDADES_CREARDIRECTORIO = 13210;
export const PERMISO__VENTAS_PREVENTA_OPORTUNIDADES_SUBIRARCHIVO = 13220;
export const PERMISO__VENTAS_PREVENTA_OPORTUNIDADES_ELIMINARARCHIVO = 13230;
export const PERMISO__VENTAS_PREVENTA_OPORTUNIDADES_DESCARGARARCHIVO = 13240;
//Plan de cuentas
export const ACCESO__VENTAS_PLANCUENTAS = 14000;
export const PERMISO__VENTAS_PLANCUENTAS_ANALIZAR = 14100;
//********* Marketing
export const ACCESO__MARKETING = 20000;
//Campañas
export const ACCESO__MARKETING_CAMPAÑAS = 21000;
export const ACCESO__MARKETING_CAMPAÑAS_CREAR = 21100;
export const PERMISO__MARKETING_CAMPÑAS_CAMPAÑAS_GRABAR = 21111;
export const PERMISO__MARKETING_CAMPÑAS_CAMPAÑAS_INICIARCAMPAÑA = 21112;
export const ACCESO__MARKETING_CAMPAÑAS_CITAS = 21120;
//Herramientas Inteligencia Artificial
export const ACCESO__MARKETING_HERRAMIENTASIA = 22000;
export const PERMISO__MARKETING_HERRAMIENTASIA_MENSAJES = 22210;
export const PERMISO__MARKETING_HERRAMIENTASIA_CUENTASSIMILARES = 22220;
export const PERMISO__MARKETING_HERRAMIENTASIA_ANALISISOPORTUNIDADES = 22230;
//Leads
export const ACCESO__MARKETING_LEADS = 23000;
export const ACCESO__MARKETING_LEADS_TODOS = 23100;
export const ACCESO__MARKETING_LEADS_NUEVOS = 23200;
//********* Operaciones
export const ACCESO__OPERACIONES = 30000;
export const ACCESO__OPERACIONES_IMPLEMENTACIONES = 31000;
export const ACCESO__OPERACIONES_ACTIVIDADES = 32000;
export const ACCESO_OPERACIONES_DOCUMENTACION = 33000;
//********** Logística
export const ACCESO__LOGISTICA = 40000;
export const ACCESO__LOGISTICA_COMPRAS = 41000;
export const ACCESO__LOGISTICA_RECEPCION = 42000;
export const ACCESO__LOGISTICA_RENOVACIONES = 43000;
export const ACCESO__LOGISTICA_COMISIONES = 44000;
//********* Contabilidad
export const ACCESO__CONTABILIDAD = 50000;
export const ACCESO__CONTABILIDAD_RECEPCIONFACTURAS = 51000;
export const ACCESO__CONTABILIDAD_PAGOS = 52000;
export const ACCESO__CONTABILIDAD_FACTURACION = 53000;
export const ACCESO__CONTABILIDAD_COBRANZA = 54000;
//********* Administración
export const ACCESO__ADMINISTRACION = 60000;
export const ACCESO__ADMINISTRACION_DATOSFINANCIEROS = 61000;
export const ACCESO__ADMINISTRACION_DOCUMENTOS = 62000;
//******** Dirección
export const ACCESO__DIRECCION = 70000;
//Dashboard
export const ACCESO__DIRECCION_DASHBOARD = 71000;
export const ACCESO__DIRECCION_DASHBOARD_GERENCIA = 71100;
export const ACCESO__DIRECCION_DASHBOARD_VENTAS = 71200;
export const ACCESO__DIRECCION_DASHBOARD_VENDEDORES = 71300;
export const ACCESO__DIRECCION_DASHBOARD_LOGISTICAPROYECTOS = 71400;
export const ACCESO__DIRECCION_DASHBOARD_LOGISTICARENOVACIONES = 71500;
export const ACCESO__DIRECCION_DASHBOARD_MARKETING = 71600;
//Reportes
export const ACCESO__DIRECCION_REPORTES = 72000;
export const ACCESO__DIRECCION_REPORTES_OPORTUNIDADES = 72100;
export const ACCESO__DIRECCION_REPORTES_MARKETING = 72150;
export const ACCESO__DIRECCION_REPORTES_VENTAS = 72200;
export const ACCESO__DIRECCION_REPORTES_VENDEDORES = 72250;
export const ACCESO__DIRECCION_REPORTES_COMISIONES = 72300;
export const ACCESO__DIRECCION_REPORTES_COMPARATIVAS = 72350;
export const ACCESO__DIRECCION_REPORTES_IMPLEMENTACION = 72400;
export const ACCESO__DIRECCION_REPORTES_ACTIVIDADES = 72400;
export const ACCESO__DIRECCION_REPORTES_PROVEEDORES = 72450;
export const ACCESO__DIRECCION_REPORTES_FACTURACION = 72500;
export const ACCESO__DIRECCION_REPORTES_RENOVACIONES = 72550;
export const ACCESO__DIRECCION_REPORTES_PROCESO = 72600;
export const ACCESO__DIRECCION_REPORTES_SEGUIMIENTO = 72650;
export const ACCESO__DIRECCION_REPORTES_PROYECTOS = 72700;
//******* Sistemas
export const ACCESO__SISTEMA = 80000;
//Configuracion
export const ACCESO__SISTEMA_CONFIGURACION = 81000;
export const ACCESO__SISTEMA_CONFIGURACION_GENERAL = 81100;
export const ACCESO__SISTEMA_CONFIGURACION_USUARIOS = 81150;
export const ACCESO__SISTEMA_CONFIGURACION_FABRICANTES = 81200;
export const ACCESO__SISTEMA_CONFIGURACION_CRM = 81250;
export const ACCESO__SISTEMA_CONFIGURACION_COTIZADOR = 81300;
export const ACCESO__SISTEMA_CONFIGURACION_OPERACIONES = 81350;
export const ACCESO__SISTEMA_CONFIGURACION_DASHBOARD = 81400;
//Cuenta
export const ACCESO__SISTEMA_CUENTA = 82000;
//***********Alcances
export const ALCANCE__TODAS_LAS_CUENTAS = 8010;
export const ALCANCE__TODOS_LOS_CONTACTOS = 8020;
export const ALCANCE__TODAS_LAS_OPORTUNIDADES = 8030;
export const ALCANCE__TODAS_LAS_PROPUESTAS = 8040;
export const ALCANCE__TODAS_LAS_CAMPAÑAS = 8050;
export const ALCANCE__TODOS_LOS_PLANES_DE_CUENTA = 8060;
export const ALCANCE__TODOS_LOS_LEADS = 8070;
export const ALCANCE__TODAS_LAS_IMPLEMENTACIONES = 8080;
//********* Chat IA */
export const ACCESO_CHAT_IA = 90000;

//Variables de los tipos de busqueda y descarga de informacion de la base de datos
export const BUSQUEDA_ACTIVIDADES_POR_USUARIO = 15101;
export const BUSQUEDA_ACTIVIDADES_POR_CATEGORIA_POR_USUARIO = 15102;
export const BUSQUEDA_LISTA_CUENTAS_CON_OPORTUNIDADES_GANADAS_O_ABIERTAS_CRM = 15103;
export const BUSQUEDA_DATOS_DE_CONTACTO = 15104;
export const BUSQUEDA_LISTA_CONTACTOS_SEGUN_CUENTA = 15105;
export const BUSQUEDA_DATOS_DE_CONTACTO_ESPECIFICO = 15106;
export const BUSQUEDA_LISTA_OPORTUNIDADES_CRM_EN_CUALQUIER_ETAPA = 15107;
export const BUSQUEDA_CONTACTO_DE_OPORTUNIDAD = 15108;
export const BUSQUEDA_VENDEDOR_DE_OPORTUNIDAD = 15109;
export const BUSQUEDA_PREVENTA_DE_OPORTUNIDAD = 15110;
export const BUSQUEDA_REGISTRO_FABRICANTES_CRM = 15111;
export const BUSQUEDA_LISTA_REGISTROS_FABRICANTE_CRM = 15112;
export const BUSQUEDA_ACTIVIDADES_AGRUPADAS = 15113;
export const BUSQUEDA_CATEGORIAS_AGRUPADAS = 15114;
export const BUSQUEDA_TIEMPO_EMPLEADO_POR_CATEGORIAS_POR_USUARIO = 15115;
export const BUSQUEDA_LISTA_OPORTUNIDADES_GANADAS = 15116;
export const BUSQUEDA_PROYECTO_REPORTE = 15117;
export const BUSQUEDA_PLAZOS_PROYECTO_REPORTE = 15118;
export const BUSQUEDA_PLAZO_EJECUTADO_PROYECTO_REPORTE = 15119;
export const BUSQUEDA_CUENTAS_CON_PROYECTOS_GANADOS_POR_ANO = 15120;
export const BUSQUEDA_SOPORTE_REPORTE = 15121;
export const BUSQUEDA_DATOS_PROYECTO_REPORTE = 15122;
export const BUSQUEDA_PLAZOS_TODOS_LOS_PROYECTOS_REPORTE = 15123;
export const BUSQUEDA_TODOS_LOS_PROYECTOS_REPORTE = 15124;
export const BUSQUEDA_LISTA_CUENTAS_CRM_INICIO = 15125;

//Variables de Modulo Logistica Entre 20001 y 20100
export const BUSQUEDA_PROPUESTAS_ACEPTADAS_PARA_REALIZAR_COMPRAS = 20001;
export const DESCARGA_PROPUESTA_ACEPTADA_PARA_REALIZAR_COMPRAS = 20002;
export const DESCARGA_ESTADO_POSTVENTA = 20003;
export const DESCARGA_ORDENES_ENVIADAS_Y_RECIBIDAS_PARA_REALIZAR_COMPRAS = 20004;
export const GRABAR_ORDENES_COMPRA_LOGISTICA = 20005;
export const CERRAR_ORDENES_COMPRA_LOGISTICA = 20006;
export const ABRIR_ORDENES_COMPRA_LOGISTICA = 20007;
export const BUSQUEDA_PROPUESTAS_ACEPTADAS_PARA_RECIBIR_MERCADERIA = 20008;

//Variables de Modulo Marketing Entre 16001 y 16100
export const GRABAR_CAMPANA_MKT = 16001;
export const LISTAR_CAMPANAS = 16002;

//Variables de Cotizador Entre 17000 y 17200
export const OPCION_MENU_CONTEXTO__AGREGAR = 17001;
export const OPCION_MENU_CONTEXTO__DESAGREGAR = 17002;
export const OPCION_MENU_CONTEXTO__COPIAR = 17003;
export const OPCION_MENU_CONTEXTO__COPIAR_TODO = 17004;
export const OPCION_MENU_CONTEXTO__PEGAR = 17005;
export const OPCION_MENU_CONTEXTO__INSERTAR = 17006;
export const OPCION_MENU_CONTEXTO__INSERTAR_AL_FINAL = 17007;
export const OPCION_MENU_CONTEXTO__ELIMINAR = 17008;
export const OPCION_MENU_CONTEXTO__DESELECCIONAR = 17009;
export const OPCION_MENU_CONTEXTO__CAMBIAR_PRC_LISTA_O_DSCTO_FAB_O_IMPORT_SIN_CAMBIAR_VENTA = 17010;
export const OPCION_MENU_CONTEXTO__CAMBIAR_VARIOS_ITEMS_A_LA_VEZ = 17011;
export const OPCION_MENU_CONTEXTO__CAMBIAR_MARGEN_O_DESCUENTO_SIN_CAMBIAR_VENTA = 17012;

//Variables de Cotizador sincronizadas con PHP Entre 17201 y 17500
export const BUSQUEDA_CODIGOS_DESDE_TABLA_FABRICANTE = 17201;
export const CREAR_CODIGO_PRODUCTO_FABRICANTE_COTIZACION = 17202;
export const DESCARGAR_NOTAS_FABRICANTE_PRODUCTOS_COTIZADOR = 17203;
export const DAR_INICIO_A_ETAPA_POSTVENTA = 17204;
export const LISTAR_ORDENES_RECIBIDAS_DE_UNA_PROPUESTA = 17205;
export const GRABAR_ORDENES_RECIBIDAS_DE_UNA_PROPUESTA = 17206;

//Variables de tipo de registro
export const REGISTRO_ACTIVIDAD_USUARIO = 20101;
